### ISSUE TITLE
NullPointerException when checking for new version

### ISSUE THREAD

**Issue by jeremybrooks** [jeremybrooks/SuprSetr#3]
```
WARN net.jeremybrooks.suprsetr.VersionChecker [VersionCheckerThread] 2016-02-15 13:16:08,747 - ERROR WHILE CHECKING FOR A NEW VERSION.
java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1155)
        at net.jeremybrooks.suprsetr.VersionChecker.run(VersionChecker.java:75)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeremybrooks** [comment]
This happens when running from the IDE, because the version comes from the manifest, which is not available when running from the IDE during development. Won't fix.
